### ISSUE TITLE
Make interpreter use arena instead of `Rc`

### ISSUE THREAD

**Issue by QnnOkabayashi** [QnnOkabayashi/curse-lang#14]
`Rc` bad. Arena good.

Can we change the `GlobalBindings` struct in the interpreter to also store a `bumpalo::Bump` or `typed_arena::Arena`, and then maybe rename it to `RuntimeState`, and make all the existing free-standing functions into methods on it so it's easy to pass around?

**Comment by William103** [comment]
Hmm. The local bindings definitely can't be in an arena, or we'd leak memory like crazy. We could put the global bindings in an arena, since they are in memory the entire runtime of the program, but then references to global values would be regular references while references to local values would be `Rc`s with different lifetimes. I have no idea how to manage all that, but am open to suggestions.

I like the idea of making everything methods on a single `RuntimeState` struct though.
